### ISSUE TITLE
Metrics Review Tracker

### ISSUE THREAD

**Issue by ptooley** [numericalalgorithmsgroup/pypop#19]
- [ ] MPI_Metrics
- [ ] MPI_OpenMP_Metrics
- [ ] MPI_OpenMP_Multiplicative_Metrics
- [ ] OpenMP_Metrics
- [ ] Judit_Hybrid_Metrics
